In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

<b> Загрузка и предобработка исходных данных

In [2]:
data = pd.read_csv("../../Практические материалы/Lab 1. Linear and logistic regression/mnist/mnist_train.csv")
data_test = pd.read_csv("../../Практические материалы/Lab 1. Linear and logistic regression/mnist/mnist_test.csv")

In [3]:
X = data.iloc[:,1:].values
X_test = data_test.iloc[:,1:].values

In [4]:
mean = np.mean(X)
std = np.std(X)

X = (X - mean)/std
X_test = (X_test - mean)/std

In [5]:
m = len(data)
n = data.shape[1]-1

In [6]:
Y = np.zeros([m,10])

In [7]:
for i in range(m):
    Y[i,data.label.values[i]] = 1

In [8]:
Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

<b> Алгоритм обратного распространения ошибки

In [9]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [10]:
def forward(W1,W2,W3,B1,B2,B3,X):
    F1 = sigmoid(np.matmul(X,W1) + B1)
    F2 = sigmoid(np.matmul(F1,W2) + B2)
    H = sigmoid(np.matmul(F2,W3) + B3)
    return F1,F2,H

In [11]:
def backpropagation(W1,W2,W3,B1,B2,B3,H,F2,F1,X):
    S3 = H - Y

    dW3 = np.matmul(np.transpose(F2),S3)
    dB3 = np.sum(S3, axis = 0)

    S2 = np.matmul(S3,np.transpose(W3))*F2*(1-F2)

    dW2 = np.matmul(np.transpose(F1),S2)
    dB2 = np.sum(S2, axis = 0)

    S1 = np.matmul(S2,np.transpose(W2))*F1*(1-F1)

    dW1 = np.matmul(np.transpose(X),S1)
    dB1 = np.sum(S1, axis = 0)
    
    return dW3,dW2,dW1,dB3,dB2,dB1

In [22]:
k1 = 100
k2 = 50
k3 = 10

W1 = np.random.rand(n,k1) - 0.5
W2 = np.random.rand(k1,k2) - 0.5
W3 = np.random.rand(k2,k3) - 0.5
B1 = np.zeros([1,k1])
B2 = np.zeros([1,k2])
B3 = np.zeros([1,k3])
dropout1 = np.round(np.random.rand(n,k1))
dropout2 = np.round(np.random.rand(k1,k2))
dropout3 = np.round(np.random.rand(k2,k3))

alpha = 0.00001

for i in range(1000):
    F1,F2,H = forward(W1*dropout1,W2*dropout2,W3*dropout3,B1,B2,B3,X)
    
    J = -np.sum((Y*np.log(H) + (1-Y)*np.log(1-H)))
    print(i,J)
    
    dW3,dW2,dW1,dB3,dB2,dB1 = backpropagation(W1*dropout1,W2*dropout2,W3*dropout3,B1,B2,B3,H,F2,F1,X)
    
    W3 = W3 - alpha*dW3
    W2 = W2 - alpha*dW2
    W1 = W1 - alpha*dW1
    B3 = B3 - alpha*dB3
    B2 = B2 - alpha*dB2
    B1 = B1 - alpha*dB1

0 16259.248518505608
1 16253.730705372585
2 16248.216385137146
3 16242.705553914551
4 16237.198207825302
5 16231.69434299519
6 16226.193955555274
7 16220.697041641915
8 16215.203597396738
9 16209.713618966656
10 16204.227102503903
11 16198.744044165984
12 16193.264440115732
13 16187.788286521301
14 16182.315579556134
15 16176.846315399012
16 16171.380490234029
17 16165.918100250636
18 16160.459141643585
19 16155.003610613012
20 16149.551503364362
21 16144.102816108463
22 16138.657545061486
23 16133.215686444963
24 16127.777236485801
25 16122.342191416288
26 16116.910547474079
27 16111.482300902213
28 16106.057447949137
29 16100.63598486869
30 16095.217907920089
31 16089.803213367974
32 16084.391897482412
33 16078.983956538885
34 16073.579386818255
35 16068.178184606873
36 16062.780346196507
37 16057.385867884312
38 16051.994745972992
39 16046.606976770601
40 16041.222556590701
41 16035.841481752319
42 16030.463748579934
43 16025.08935340348
44 16019.71829255843
45 16014.350562385673
46

365 14450.046409831513
366 14445.589330613371
367 14441.134681898222
368 14436.682461618877
369 14432.232667711498
370 14427.785298115628
371 14423.340350774128
372 14418.89782363321
373 14414.45771464239
374 14410.02002175453
375 14405.58474292576
376 14401.151876115538
377 14396.7214192866
378 14392.293370404956
379 14387.867727439872
380 14383.44448836391
381 14379.023651152844
382 14374.605213785726
383 14370.189174244795
384 14365.775530515555
385 14361.36428058673
386 14356.955422450188
387 14352.548954101068
388 14348.144873537649
389 14343.743178761424
390 14339.34386777703
391 14334.946938592273
392 14330.552389218112
393 14326.16021766865
394 14321.77042196114
395 14317.383000115939
396 14312.997950156545
397 14308.615270109543
398 14304.234958004652
399 14299.85701187465
400 14295.481429755419
401 14291.10820968592
402 14286.737349708168
403 14282.36884786725
404 14278.002702211297
405 14273.638910791484
406 14269.277471662022
407 14264.918382880156
408 14260.561642506142
40

724 12992.23059909773
725 12988.533538251952
726 12984.83832278936
727 12981.144951375194
728 12977.453422675657
729 12973.763735357881
730 12970.075888089948
731 12966.389879540882
732 12962.705708380623
733 12959.023373280015
734 12955.342872910856
735 12951.66420594585
736 12947.987371058598
737 12944.312366923614
738 12940.639192216326
739 12936.96784561304
740 12933.298325790978
741 12929.63063142824
742 12925.964761203793
743 12922.300713797518
744 12918.638487890135
745 12914.978082163287
746 12911.31949529943
747 12907.662725981916
748 12904.007772894962
749 12900.35463472361
750 12896.703310153782
751 12893.053797872248
752 12889.406096566594
753 12885.760204925291
754 12882.116121637599
755 12878.473845393622
756 12874.833374884343
757 12871.194708801491
758 12867.557845837675
759 12863.922784686294
760 12860.28952404156
761 12856.658062598523
762 12853.028399052995
763 12849.400532101638
764 12845.774460441866
765 12842.150182771933
766 12838.527697790856
767 12834.907004198

<b> Численная проверка градиента

In [199]:
F1,F2,H = forward(W1,W2,W3,B1,B2,B3,X)

J1 = -np.sum((Y*np.log(H) + (1-Y)*np.log(1-H)))

B1[0,9] += 0.0001

F1,F2,H = forward(W1,W2,W3,B1,B2,B3,X)

J2 = -np.sum((Y*np.log(H) + (1-Y)*np.log(1-H)))

B1[0,9] -= 0.0001

print((J2-J1)/0.0001)

2.520474372431636


<b> Расчёт предсказаний для тестовой выборки

In [13]:
_,_,pred = forward(W1*dropout1,W2*dropout2,W3*dropout3,B1,B2,B3,X_test)

In [14]:
pred

array([[3.82832338e-03, 1.44951786e-03, 2.89113870e-03, ...,
        9.84691764e-01, 7.92870749e-05, 3.91098438e-03],
       [2.62074789e-03, 1.48107208e-03, 9.76552557e-01, ...,
        2.92722291e-05, 2.15340972e-03, 1.35513302e-05],
       [1.88055091e-06, 9.94892430e-01, 1.20356745e-03, ...,
        8.82477285e-03, 1.06168991e-03, 2.79920005e-03],
       ...,
       [1.17421379e-05, 8.36072324e-04, 6.10546849e-04, ...,
        1.48529165e-03, 9.96415639e-03, 2.55003041e-03],
       [1.59252617e-03, 8.17167667e-03, 2.04051592e-04, ...,
        2.91044255e-04, 1.33763046e-01, 4.25344026e-05],
       [3.90082536e-03, 5.93716840e-04, 5.18135333e-03, ...,
        5.57671510e-05, 7.48158424e-05, 2.31811267e-04]])

In [15]:
pred = np.argmax(pred,axis=1)

In [16]:
pred

array([7, 2, 1, ..., 4, 5, 6])

In [17]:
data_test.label

0       7
1       2
2       1
3       0
4       4
       ..
9995    2
9996    3
9997    4
9998    5
9999    6
Name: label, Length: 10000, dtype: int64

In [18]:
np.mean(data_test.label == pred)

0.941

In [19]:
data_test['pred'] = pred

In [20]:
for i in range(10):
    temp = data_test[data_test.label == i]
    print(np.mean(np.mean(temp.label == temp.pred)))

0.9795918367346939
0.9797356828193833
0.9282945736434108
0.9346534653465347
0.9480651731160896
0.9080717488789237
0.9582463465553236
0.9280155642023347
0.919917864476386
0.9187314172447968
